### ISSUE TITLE
Questions about repository maintenance and purpose

### ISSUE THREAD

**Issue by gaikaz** [odoomates/odooapps#1]
Hi.
First of all, thank you for porting the now missing modules from Oodo 11.0 to Odoo 12.0

As I see, this is quite a fresh repository and I have a few questions about it.

1. What kind of modules can be expected to be added here?
2. How much will it be maintained?
3. Will you be accepting PRs?

These questions came up when I tried using module `om_account_asset` and it uses translations from Odoo 11.0 original module `account_asset`, which don't fully work for Odoo 12.0
I'm just wondering, if I should be creating issues in this repository about general problems like that.

Thanks.

**Comment by odoomates** [comment]
Hi,
1. We are not yet focused on any particular domain. We are contributing modules from all the domain like accounting, point of sale, inventory etc

2. As you mentioned in the post the repo is fresh one, regarding the maintenance the issues and PR is welcomed

3. Yet we haven't received any PR yet in the repository, we will review those PR and merge if we feel it necessary and useful for the end users

If you have PR for the account_asset translation, please don't hesitate to create a PR


Thanks

**Comment by gaikaz** [comment]
Thanks for the detailed response 😊

Would you consider adding information like this to the `README.md` file?
It would be very useful to see information about the purpose of this repository and modules inside. Maybe even your guidelines for contributing here.

**Comment by odoomates** [comment]
Sure we will update it
