### ISSUE TITLE
[16.0] om_account_accountant: You can't create a new statement line

### ISSUE THREAD

**Issue by nagybal** [odoomates/odooapps#101]
Creating new lines at the Cash Statment is bugged, if You try to click on the "Create and Edit" button, You get the attached error. "You can't create a new statement line without a suspense account set on the Miscellaneous Operations journal."

As a workaround, You can create the same lines on the list view, one by one. (It took me a whole day of troubleshooting to figure this out. Pretty annoying!)

![create and edit](https://user-images.githubusercontent.com/27618042/235685646-b656ca46-2040-4313-b7d2-055b33c07267.png)
![cant create lines](https://user-images.githubusercontent.com/27618042/235685652-d4f01500-19c1-4f79-b6dc-36961a6133a3.png)

**Comment by Maximvdw** [comment]
Hey, did you ever find out how to solve this issue - seeing you closed it as "not planned"?
