### ISSUE TITLE
[16.0] [major bug] om_account_accountant: Multi currency exchange

### ISSUE THREAD

**Issue by nagybal** [odoomates/odooapps#108]
Internal transfer (basically an exchange) from an EUR to a HUF account (my base currency is HUF), om_account_accountant creates the two entries on both of the journals.

The bug is:
the journal entry on the destination account keeps the original currency. It should change and the "Amount in Currency" as well!

The bank credits the destination account in HUF. The journal must also show HUF.

This is a major issue because You can not reconcile the incorrect entry with the bank statement (In my example the 100.000 with 39.667.000 !!! )

Please find screenshots below:
![Screen Shot 2023-08-08 at 15 47 00](https://github.com/odoomates/odooapps/assets/27618042/6e13448f-ebff-41ee-a464-161a02c381c5)

**Comment by niyasraphy** [comment]
hi @nagybal ,
could you see if this is reproducible in odoo runbot and if yes, please report it in: https://github.com/odoo/odoo/issues

i believe this is feature is from core odoo.

thanks

**Comment by nagybal** [comment]
@niyasraphy thank you for the tip. Indeed, the same issue also appears on the 16.3 enterprise test server. Who do You think I need to mention at https://github.com/odoo/odoo/issues/131978 so the ticket is assigned to someone?

**Comment by niyasraphy** [comment]
hi @nagybal ,
could you please remove the reference to om_account_accountant from this ticket: https://github.com/odoo/odoo/issues/131978 as it is a issue in odoo core.

thanks
