### ISSUE TITLE
[16.0][om_account_accountant] Show Full Accounting Group no longer visible after install of om_account_accountant

### ISSUE THREAD

**Issue by kwoychesko** [odoomates/odooapps#113]
After installation of the om_account_accountant module, you can no longer see the Show Full Accounting Group in the Groups list, as can be seen in the following video:
https://www.dropbox.com/scl/fi/74518fr028gx41jpu8hnk/Missing-Full-Accounting-Group.mp4?rlkey=co8z1s51c17vsq77llnmw4uvj&dl=0

I'm happy to contribute by troubleshooting the code, but I have no idea where to start... any hints? :-)

Also happy to code a fix if I find the location of the problem.

Thanks for the great module!

**Comment by odoomates** [comment]
Hi,
This is expected behavior, once the module is installed full accounting feature will be automatically installed and we just renamed the group to "Accountant" as in odoo enterprise.
