### ISSUE TITLE
[13.0]om_account_asset: error no price_subtotal_signed & date_invoice

### ISSUE THREAD

**Issue by SmithLin0618** [odoomates/odooapps#12]
I made the following input(accounting>customers>invoices)

![image](https://user-images.githubusercontent.com/38001362/68536786-7074cc80-0393-11ea-92c4-d54232f2aa3d.png)

When executing 【Save】, the following error will be run.

![image](https://user-images.githubusercontent.com/38001362/68536776-28ee4080-0393-11ea-8366-5c0d4b481524.png)

I made the following input(accounting>Venders>Bills)

![image](https://user-images.githubusercontent.com/38001362/68536827-204a3a00-0394-11ea-8345-5531fca0a2dd.png)

When executing 【Save】, the following error will be run.
![image](https://user-images.githubusercontent.com/38001362/68536829-335d0a00-0394-11ea-8e4b-fc0732003e75.png)

**Comment by odoomates** [comment]
Hi,
Thanks for reporting. Fixed 
Thanks
