### ISSUE TITLE
[13.0]om_account_asset l can not save Asset Category in Bills

### ISSUE THREAD

**Issue by SmithLin0618** [odoomates/odooapps#14]
When I create a bill and enter the asset category, click save, the asset category that was originally entered will be cleared
This issue prevents this module from working properly
【before save】
![image](https://user-images.githubusercontent.com/38001362/71572043-4bd9dd00-2b18-11ea-87c3-1d3d5905db7a.png)
【after save】
![image](https://user-images.githubusercontent.com/38001362/71572065-61e79d80-2b18-11ea-9f55-710f5898a332.png)

**Comment by odoomates** [comment]
Hi,
Thanks for reporting, we have fixed it. Please get the latest and please check once again.

**Comment by SmithLin0618** [comment]
I have try the new addons
but I found that issue didn't fix

**Comment by SmithLin0618** [comment]
i have try by this gif.
![9dd0s-nnt7h](https://user-images.githubusercontent.com/38001362/71787881-efb31380-3057-11ea-84ab-f32d383de7fd.gif)

**Comment by odoomates** [comment]
resolved
