### ISSUE TITLE
om_account_followup Email template doesnt works

### ISSUE THREAD

**Issue by danylook** [odoomates/odooapps#144]
i rewrite the email template for email overdue reminder becouse the actual one doesnt get anythink

<table border="0" cellpadding="0" cellspacing="0" style="box-sizing:border-box;padding-top: 16px; background-color: #F1F1F1; font-family:Verdana, Arial,sans-serif; color: #454748; width: 100%; border-collapse:separate;" width="100%">
  <tbody>
    <tr>
      <td align="center">
        <table border="0" cellpadding="0" cellspacing="0" width="590" style="box-sizing:border-box;padding: 16px; background-color: white; color: #454748; border-collapse:separate;">
          <tbody>
            
            <tr>
              <td align="center" style="min-width: 590px;">
                <table border="0" cellpadding="0" cellspacing="0" width="590" style="box-sizing:border-box;min-width: 590px; background-color: white; padding: 0px 8px 0px 8px; border-collapse:separate;">
                  <tbody>
                    <tr>
                      <td valign="middle">
                        <span style="font-size: 15px;">Payment Reminder</span><br>
                        <span style="font-size: 20px; font-weight: bold;"></span>
                      </td>
                      <td valign="middle" align="right">
                        <img t-attf-src="/logo.png?company={{ object.company_id.id }}" style="border-style: none; box-sizing: border-box; vertical-align: middle; padding: 0px; margin: 0px; height: auto; width: 80px; object-fit: cover;" t-att-alt="object.company_id.name" width="80" height="0">
                      </td>
                    </tr>
                    <tr>
                      <td colspan="2" style="text-align:center;">
                        <hr width="100%" style="overflow-wrap:unset;border-style:none;border-top-width:medium;border-left-width:medium;border-bottom-width:medium;border-right-width:medium;overflow-y:visible;overflow-x:visible;height:0px;box-sizing:content-box;background-color:#cccccc;border:medium none;clear:both;display:block;font-size:0px;min-height:1px;line-height:0; margin: 16px 0px 16px 0px;">
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            
            <tr>
              <td align="center" style="min-width: 590px;">
                <table border="0" cellpadding="0" cellspacing="0" width="590" style="box-sizing:border-box;min-width: 590px; background-color: white; padding: 0px 8px 0px 8px; border-collapse:separate;">
                  <tbody>
                    <tr>
                      <td valign="top" style="font-size: 13px;">
                        <div>
                          Dear <t t-out="object.name or ''">Marc Demo</t>,<br><br>
                          Exception made if there was a mistake of ours, it seems that the following amount stays unpaid. Please, take appropriate measures in order to carry out this payment in the next 8 days. Would your payment have been carried out after this mail was sent, please ignore this message. Do not hesitate to contact our accounting department.<br>
                          Regards,
                          <t t-if="user.signature">
                            <br>
                            <t t-out="user.signature or ''"><br>Mitchell Admin</t>
                           <t t-out="object.debt_balance or ''"><br>Mitchell Admin</t>
<br>
                          </t>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td style="text-align:center;">
                        <hr width="100%" style="overflow-wrap:unset;border-style:none;border-top-width:medium;border-left-width:medium;border-bottom-width:medium;border-right-width:medium;overflow-y:visible;overflow-x:visible;height:0px;box-sizing:content-box;background-color:#cccccc;border:medium none;clear:both;display:block;font-size:0px;min-height:1px;line-height:0; margin: 16px 0px 16px 0px;">
                      </td>
                    </tr>
                    <tr>
                      <td>
                      <br></td>
                    </tr>
                  </tbody>
                </table>
              </td>
			  <table style="border-spacing: 0; border-collapse: collapse; width: 100%; text-align: center;">
				<tr>
				  <th style="padding: 5px; border: 1px solid black;">Invoice Number</th>
				  <th style="padding: 5px; border: 1px solid black;">Invoice Date</th>
				  <th style="padding: 5px; border: 1px solid black;">Payment Terms</th>
				  <th style="padding: 5px; border: 1px solid black;">Due Date</th>
				  <th style="padding: 5px; border: 1px solid black;">Order Ref.</th>
				  <th style="padding: 5px; border: 1px solid black;">Type</th>
				  <th style="padding: 5px; border: 1px solid black;">Total Untaxed</th>
				  <th style="padding: 5px; border: 1px solid black;">Total</th>
				  <th style="padding: 5px; border: 1px solid black;">Residual</th>
				  <th style="padding: 5px; border: 1px solid black;">Past Reminders</th>
				</tr>
				<t t-foreach="object.invoice_ids.sorted(key=lambda inv: inv.invoice_date or datetime.date.min)" t-as="inv">
					<tr style="background-color: % if inv.move_type == 'out_refund': LightGray % endif">
						<td style="padding: 5px; border: 1px solid black;">
							<t t-out="inv.name"/>
						</td>
					</tr>
				</t>
					<td style="padding: 5px; border: 1px solid black;">
					  <t t-out="inv.invoice_date"/>
					</td>
					<td style="padding: 5px; border: 1px solid black;">
					  <t t-out="inv.invoice_payment_term_id.name or ''"/>
					</td>
					<td style="padding: 5px; border: 1px solid black;">
					  <t t-out="inv.invoice_date_due"/>
					</td>
					<td style="padding: 5px; border: 1px solid black;">
					  <t t-out="inv.ref or ''"/>
					</td>
					<td style="padding: 5px; border: 1px solid black;"><t t-out="dict(inv.fields_get(allfields=['move_type'])['move_type']['selection'])[inv.move_type]"/></td>
					<td style="padding: 5px; border: 1px solid black; text-align: right;">
					  <t t-out="format_amount(inv.amount_untaxed * (inv.move_type == 'out_refund' and -1 or 1), inv.currency_id)"/>
					</td>
					<td style="padding: 5px; border: 1px solid black; text-align: right;">
					  <t t-out="format_amount(inv.amount_total * (inv.move_type == 'out_refund' and -1 or 1), inv.currency_id)"/>
					</td>
					<td style="padding: 5px; border: 1px solid black; text-align: right;">
					  <t t-out="format_amount(inv.amount_residual * (inv.move_type == 'out_refund' and -1 or 1), inv.currency_id)"/>
					</td>
				  </tr>
				</t>
			  </table>
            </tr>
            
            <tr>
              <td align="center" style="min-width: 590px;">
                <table border="0" cellpadding="0" cellspacing="0" width="590" style="box-sizing:border-box;min-width: 590px; background-color: white; font-size: 11px; padding: 0px 8px 0px 8px; border-collapse:separate;">
                  <tbody>
                    <tr>
                      <td valign="middle" align="left">
                        <t t-out="object.company_id.name or ''">YourCompany</t>
                      </td>
                    </tr>
                    <tr>
                      <td valign="middle" align="left" style="opacity: 0.7;">
                        <t t-out="object.company_id.phone or ''">+1 650-123-4567</t>
                        <t t-if="object.company_id.email">
                          | <a t-att-href="'mailto:%s' % object.company_id.email" style="box-sizing:border-box;background-color:transparent;text-decoration:none; color: #454748;" t-out="object.company_id.email or ''">info@yourcompany.com</a>
                        </t>
                        <t t-if="object.company_id.website">
                          | <a t-att-href="'%s' % object.company_id.website" style="box-sizing:border-box;background-color:transparent;text-decoration:none; color: #454748;" t-out="object.company_id.website or ''">http://www.example.com</a>
                        </t>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
    
    <tr>
      <td align="center" style="min-width: 590px;">
        <table border="0" cellpadding="0" cellspacing="0" width="590" style="box-sizing:border-box;min-width: 590px; background-color: #F1F1F1; color: #454748; padding: 8px; border-collapse:separate;">
          <tbody>
            <tr>
              <td style="text-align: center; font-size: 13px;">
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>

**Comment by odoomates** [comment]
Hi, 
we made a fix as part of another bug report in the commit: https://github.com/odoomates/odooapps/commit/937988cb90165819de5a2705ad1add1f8aebdb46

can you try with latest code and see if the issue still persists or not, if still there, please let us know

**Comment by danylook** [comment]
hi 
i try but doesnt works for odoo 15 with the Markup modification

![Untitled](https://github.com/user-attachments/assets/94ba3451-e53f-4478-a126-ab8997943757)

the odoo dont recognize the ${xxx} statement. need to use {{xxxx}} 

thanks for your help

**Comment by danylook** [comment]
[follow email template.zip](https://github.com/user-attachments/files/16676965/follow.email.template.zip)
this is my solution. 
I'm a very junior programer.
sorry if i dont follow the correct rules.
Regards
Daniel

**Comment by odoomates** [comment]
hi @danylook ,
thanks for bringing attention

the issue has been fixed by this commit:  https://github.com/odoomates/odooapps/commit/fbf8fd581079aaf51a38930bb34c98fd4dade945

based on the PR:  https://github.com/odoomates/odooapps/pull/145
