### ISSUE TITLE
[QUESTION] Why your modules are no longer available on Odoo App Store? 

### ISSUE THREAD

**Issue by anisbazmi9** [odoomates/odooapps#26]
Looks like your modules are no longer available on Odoo App store ? May I know the reason ? any legal dispute that we should be aware about before using your modules ? 

@Yenthe666 @odoomates

**Comment by odoomates** [comment]
Hi,
All the modules are back in the store.

Thanks

**Comment by odoomates** [comment]
https://apps.odoo.com/apps/modules/browse?price=Free&author=Odoo+Mates
