### ISSUE TITLE
[14.0] Bank statement import is only importing last row from the Excel template as many times as there are rows in the bank statement

### ISSUE THREAD

**Issue by salmemik** [odoomates/odooapps#28]
Please see the attached image where there is Excel template with 2 bank statement rows and screenshot from the Odoo after that has been imported. Only the last row in the bank statement has been imported 2 times (because there were 2 rows in the Excel).

Note that module is also adding ".0" to the label. My target is to import Payment Reference in the Label column and use that for reconciliation. Workaraund to solve that .0-issue is to change Excel field format from General to Text.

Thanks for your support,
Mikko

![image](https://user-images.githubusercontent.com/11749898/111905634-5225e300-8a55-11eb-9a8a-76c2717c497e.jpeg)

**Comment by odoomates** [comment]
Thanks for reporting.
Fixed: https://github.com/odoomates/odooapps/commit/ad1281367184113cd7d1c57eeba66f89f6f81394

Please have a look and let us know

**Comment by salmemik** [comment]
> Thanks for reporting.
> Fixed: [ad12813](https://github.com/odoomates/odooapps/commit/ad1281367184113cd7d1c57eeba66f89f6f81394)
> 
> Please have a look and let us know

Wow, that was fast! Tested & OK. If there is number in Label column, it is still adding than .0 decimal but I can handle that by formatting Excel cells to text. Thanks!

Mikko
