### ISSUE TITLE
[14.0] om_account_accountant : Settings - Technical - Sequences & Identifiers - Sequences - INVOICE not available

### ISSUE THREAD

**Issue by yboujraf** [odoomates/odooapps#30]
Dear,

I installed the "om_account_accountant".

I am trying to configure the "Settings - Technical - Sequences & Identifiers - Sequences" for INVOICE but not available.

![image](https://user-images.githubusercontent.com/6151258/113241794-ab8cde00-92af-11eb-95d5-c44939e07225.png)

I have found the sequence for the INVOICE is stored in "Journals / Customer Invoices"

![image](https://user-images.githubusercontent.com/6151258/113241605-50f38200-92af-11eb-8710-bdb0bdd06600.png)

But no way to create "Prefix" and "suffix" like "Sales Order"

![image](https://user-images.githubusercontent.com/6151258/113241895-eabb2f00-92af-11eb-83ad-674268def7d9.png)

Thanks if you could route me to the correct path.

Best Regards,

**Comment by odoomates** [comment]
In v14, odoo has updated the logic of sequence in the invoice. If you need to do re-sequencing in Odoo 14, see this method introduced by odoo: https://www.youtube.com/watch?v=1OlfwZcPlrg

**Comment by yboujraf** [comment]
Dear @odoomates 

Thanks for the reply.
I followed how to re-sequence but don't know how to reassign the Index incremented by ODOO if I cancelled an invoice?

Best Regards,

**Comment by odoomates** [comment]
cancelled invoice will still hold the number and next creating invoice will be incremental value of the last created invoice.
You can try it in a test database and let us know

**Comment by yboujraf** [comment]
Dear @odoomates 

Thanks for the feedback. I will try it and let you know as soon.

Best Regards,
