### ISSUE TITLE
[14.0] Community Edition - Create New fiscal Year and Periods (Monthly or quarterly)

### ISSUE THREAD

**Issue by yboujraf** [odoomates/odooapps#31]
Dear,

Only missing to start using the accounting.

Can't find how to create a new fiscal year with periods (Monthly or Quarterly and Opening - closing period)?

Best Regards,

**Comment by odoomates** [comment]
Hi,
The menu has been added. 
Accounting -> Configuration -> Accounting -> Fiscal Year.

See: https://github.com/odoomates/odooapps/commit/8b86173ebf8ac143de6445d183434322910e3f37

**Comment by odoomates** [comment]
For handling monthly periods, you can try as follows.
![Screenshot from 2021-04-12 19-13-24](https://user-images.githubusercontent.com/40998866/114426992-4d230200-9bc3-11eb-8f31-01abfbaf1d3a.png)
