### ISSUE TITLE
【14.0】om_account_asset ：when value_residual is zero but asset state not change to close

### ISSUE THREAD

**Issue by SmithLin0618** [odoomates/odooapps#35]
The asset value is zero (like below ) 
![image](https://user-images.githubusercontent.com/38001362/117122705-ba901000-adc8-11eb-92ec-470ae0398b41.png)

but state not change to close

**Comment by odoomates** [comment]
Hi,
Did you post the generated entries ?

**Comment by ABMMK** [comment]
Dear odoomates team, i am facing that issue v14 even i posted all journal entries
