### ISSUE TITLE
Persian Calendar

### ISSUE THREAD

**Issue by saeed-raeisi** [odoomates/odooapps#40]
Hello
Do you have a solution to add Persian calendar to the modules?
Or a way to add a date or change the date in -> web/static/src/js/control_panel/search_utils.js

persian odoo:
https://github.com/parodoo/parOdoo
jalali date time :
https://pypi.org/project/jdatetime/
https://jdf.scr.ir/
Jalaali date system support
https://github.com/fullcalendar/fullcalendar/issues/1813

**Comment by odoomates** [comment]
Not related with any of the modules in this repository
