### ISSUE TITLE
[14.0] om_account_asset: Duplicate messages posted to chatter if asset type has Group Journal Entries set

### ISSUE THREAD

**Issue by kwoychesko** [odoomates/odooapps#52]
When the cron job runs to post depreciation lines, one of the tasks performed is posting a message to the chatter about what it has done. If an asset type has Group Journal Entries set, then all of its related assets' chatters will have messages posted twice. This is because the method `post_lines_and_close_asset` is called twice for grouped assets.
First call in `create_grouped_move`:
![image](https://user-images.githubusercontent.com/39575203/146854793-6b68a331-0f4c-4d1b-80be-cd5cd8f33175.png)

Second call:
In the above method, the method `post` is called, which again calls `post_lines_and_close_asset`:

![image](https://user-images.githubusercontent.com/39575203/146854919-f7af6812-5e8c-429f-acac-ff5195d3225e.png)

This results in the message being posted twice:
![image](https://user-images.githubusercontent.com/39575203/146854019-4d98f700-da24-4e42-b896-2ed11dc66702.png)

The first call should be removed (i.e. in the `create_grouped_move` method.) This solves the problem, and will make the code more similar to the code for non-grouped asset types (i.e. the `create_move` method).

**Comment by odoomates** [comment]
Resolved with your merged PR:  https://github.com/odoomates/odooapps/commit/2b9e38b31428ad6c76c4fa206883e9712a8d9f84
Thanks again
