### ISSUE TITLE
[14.0] om_account_asset: assets purchased in foreign currency booked at wrong value

### ISSUE THREAD

**Issue by kwoychesko** [odoomates/odooapps#53]
When purchasing a fixed asset in foreign currency, the asset's value is created at the foreign currency purchase price instead of being converted to the company's local currency, yet the currency for the asset is set in the local currency. For example:

1. Create a company with local currency CAD.
2. Enable multi-currencies and enter an exchange rate for USD of 0.8
3. Create a Purchase Order in USD (i.e. the foreign currency) for a product that has been setup to create a fixed asset. Amount: USD$1,000
4. Create the Vendor Bill for USD$1,000.
5. The asset is created with the currency symbol set as "CAD" and the value of $1,000 ==> the correct value is $1,250.00 (i.e. $1,000 / 0.8 = $1,250). The symbol "CAD" is correct. Under GAAP and IFRS accounting rules an asset is tracked in the company's local currency even if it was purchased in foreign currency. I'm not sure about other accounting standards.

I tested Odoo CE v11's built-in account_asset module and it works according to GAAP and IFRS. For example:

1. Create a company with local currency CAD.
2. Enable multi-currencies and enter an exchange rate for USD of 0.8
3. Create a Purchase Order in USD (i.e. the foreign currency) for a product that has been setup to create a fixed asset. Amount: USD$1,000
4. Create the Vendor Bill for USD$1,000.
5. The asset is created with the value of CAD$1,250. and with depreciations in CAD.

Possible solution:
The problem is because we are using the value from the account_move_line's price_subtotal field (File: om_account_asset/models/account_move.py. Class: AccountMoveLine. Method: asset_create). I think we could use the debit field instead, but I don't know enough about the accounting model to be 100% sure.

**Comment by niyasraphy** [comment]
Fixed: 1277457969e632499aa7b9a437bbe6afd3085daa
can you review ?

**Comment by kwoychesko** [comment]
Looks great! Thank you!
