### ISSUE TITLE
om_account_asset: Thoughts on converting float fields to monetary?

### ISSUE THREAD

**Issue by kwoychesko** [odoomates/odooapps#54]
The asset module uses float fields for all currency fields and I'm wondering if we should change them to "monetary" fields?
Reasons:

1. The current float fields are not rounded, and as a result the database stores values with many more decimal places than the company currency (see image below). Maybe this is okay & normal in the Odoo development world?
2. A lot of work is done using float_compare and decimal precision, and I wonder if we made the fields monetary would some of this extra work go away?

Would love your thoughts.

Ken

![image](https://user-images.githubusercontent.com/39575203/147584472-1eacedb1-5f71-411a-8fa8-f18ffb548e62.png)

**Comment by odoomates** [comment]
Thanks for bring the attention and yes we can make it Monetary for better working of the system

**Comment by niyasraphy** [comment]
Fixed: 1277457969e632499aa7b9a437bbe6afd3085daa

**Comment by kwoychesko** [comment]
It's funny: the fields are still stored in the database in the same way. Is Odoo's "Monetary" field type is mostly a display convenience?

![image](https://user-images.githubusercontent.com/39575203/147795393-a2d14139-32b9-4b30-a27b-17d90c053a5d.png)

**Comment by kwoychesko** [comment]
I'll close this--fix looks great!
