### ISSUE TITLE
om_account_asset: Modify Depreciation method lets you delete final unposted depreciation line

### ISSUE THREAD

**Issue by kwoychesko** [odoomates/odooapps#57]
(PR Incoming) The Modify Depreciation method lets you change the number of depreciations on an open asset. If you set the new depreciation value too low, you could delete the final unposted depreciation line, which means your asset will never fully depreciate.

![image](https://user-images.githubusercontent.com/39575203/149680801-94bed8ac-9c40-46df-88f0-e725364e3fed.png)

**Comment by odoomates** [comment]
Merged: 10cd23dad643f2751428e5918ca7d9fd44eb9297
