### ISSUE TITLE
[Odoo 15.0] - [om_hr_payroll] - Refund Issue

### ISSUE THREAD

**Issue by saeedtowaileb** [odoomates/odooapps#60]
module: om_hr_payroll
version: 15.0

**Steps to reproduce**

1- Using fresh Odoo 15.0
2- Install om_hr_payroll
3- Create Salary Rule with Input (using python code e.g. inputs.XYZ.amount)
4- Create Payslip and Confirm, payslip will be created without any issues
5- Refund the same payslip

**Current behavior**
User Error: Wrong python code defined for salary rule ... (XYZ)

**Expected behavior**
Refund should be created.

**Notes**: it seems when the payslip is copied, the inputs(`input_line_ids`) are not copied in the refund, setting `copy=True` in `input_line_ids` seems to solve the issue.
[Go To Line](https://github.com/odoomates/odooapps/blob/f9f9b3d2f2072b9421aa16582241c2843a063f84/om_hr_payroll/models/hr_payslip.py#L53)

**Comment by saeedtowaileb** [comment]
Hello,

Please check the attached video.

https://user-images.githubusercontent.com/22477263/154434862-b69e48a1-1a53-4468-a8e4-d8bb1c2a541f.mp4

**Comment by odoomates** [comment]
Thanks for the video.
Will check and get back to you

**Comment by odoomates** [comment]
Closed with merging of the PR: f6aedbd46ae290e2739573e3f6d3088df796e0d6
