### ISSUE TITLE
[Odoo 15.0] - [accounting_pdf_reports] - Filters Issue

### ISSUE THREAD

**Issue by saeedtowaileb** [odoomates/odooapps#62]
module: accounting_pdf_reports
version: 15.0

Steps to reproduce

1- Install accounting_pdf_reports
2- Print General Ledger and set filters such as from date , to date , entries ..etc

**Current behavior**
The printed data in the general ledger report is not filtered based on the set filters, e.g. if you set the dates, there will be items outside of that period.

**Expected behavior**
The data in the general ledger should be filtered based on the set filters in the wizard.

**Comment by odoomates** [comment]
Thanks for reporting.
Fixed with this commit: ed877deda1032fb7dee7099692f9354cef4875ed

Can you check and let us know the feedback

**Comment by saeedtowaileb** [comment]
The issue is fixed, thank you.

**Comment by odoomates** [comment]
So we are closing this and hope you will cross check all the other reports more closely and in case if you find any other issues, feel free to open a new issue.

Thanks for using our module.
Feel free to mark you review here in this links: https://apps.odoo.com/apps/modules/15.0/om_account_accountant/
