### ISSUE TITLE
ERROR: null value in column "date" violates not-null constraint

### ISSUE THREAD

**Issue by HTPit** [odoomates/odooapps#64]
Odoo 13

When Asset is created directly within a Journal Entry (type = entry), attempting to Post returns error within UI

The operation cannot be completed:
- Create/update: a mandatory field is not set.
- Delete: another model requires the record being deleted. If possible, archive it instead.

Model: Asset/Revenue Recognition (account.asset.asset), Field: Date (date)

and error within DB

2022-04-22 01:54:00,068 6186 ERROR test odoo.sql_db: bad query: INSERT INTO "account_asset_asset" ("id", "create_uid", "create_date", "write_uid", "write_date", "account_analytic_id", "active", "category_id", "code", "company_id", "currency_id", "date", "date_first_depreciation", "invoice_id", "method", "method_end", "method_number", "method_period", "method_progress_factor", "method_time", "name", "partner_id", "prorata", "state", "value") VALUES (nextval('account_asset_asset_id_seq'), 2, (now() at time zone 'UTC'), 2, (now() at time zone 'UTC'), NULL, true, 1, '1', 1, 2, NULL, 'manual', 9, 'linear', NULL, 5, 12, 0.3, 'number', '1', NULL, false, 'draft', 0.0) RETURNING id
ERROR: null value in column "date" violates not-null constraint

Referencing: https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_move.py

    @api.model
    def _get_default_invoice_date(self):
        return fields.Date.context_today(self) if self._context.get('default_type', 'entry') in self.get_purchase_types(include_receipts=True) else False

invoice_date is False

Hence asset_create() within https://github.com/odoomates/odooapps/blob/15.0/om_account_asset/models/account_move.py gets False resulting in error.

            vals = {
                'name': self.name,
                'code': self.name or False,
                'category_id': self.asset_category_id.id,
                'value': price_subtotal,
                'partner_id': self.move_id.partner_id.id,
                'company_id': self.move_id.company_id.id,
                'currency_id': self.move_id.company_currency_id.id,
                'date': self.move_id.invoice_date,
                'invoice_id': self.move_id.id,
            }

**Comment by HTPit** [comment]
Posting self fix:

@account_move.py::

    def asset_create(self):
        ...
                #'date': self.move_id.invoice_date,
                'date': self.move_id.invoice_date if self.move_id.invoice_date else self.move_id.date,
                ...

**Comment by odoomates** [comment]
@HTPit Thanks for the fix, we will review and merge it in the module

**Comment by odoomates** [comment]
Fixed/Merged with b14a924f529597c72f93217a686de234348e0541
