### ISSUE TITLE
[15.0] Partner Ledger under Partners

### ISSUE THREAD

**Issue by hussain** [odoomates/odooapps#65]
Since there is no Odoo standard Due Payment report for partners, the Partner Ledger report can be used as a useful report to print partner balance report (Partner Ledger).

![image](https://user-images.githubusercontent.com/31601080/167873493-c55fd208-9398-41a7-be59-c752719da46e.png)

We have tested the change by adding below snippet to `accounting_pdf_reports/wizard/partner_ledger.xml`

```
<!-- Add to Partner Print button -->
    <record id="action_partner_report_partnerledger" model="ir.actions.act_window">
        <field name="name">Balance Statement (Partner Ledger)</field>
        <field name="res_model">account.report.partner.ledger</field>
        <field name="view_mode">form</field>
        <field name="view_id" ref="account_report_partner_ledger_view" />
        <field name="target">new</field>
        <field name="binding_model_id" ref="base.model_res_partner" />
        <field name="binding_type">report</field>
        <field name="context">{
            'default_partner_ids':active_ids,
            'default_target_move': 'posted',
            'default_result_selection': 'customer_supplier',
            'default_reconciled': True,
        }</field>
    </record>
```

Any idea if this should have some security group? before we create a PR.

**Comment by odoomates** [comment]
Thanks for the idea and it will good if we can add it. We reviewed the code, if you agree can we set the billing group for this action ?
also how about hiding the partner field from the wizard once we trigger the form the partner form using the context.
Hiding field using context: https://www.youtube.com/watch?v=vo15ytoW8Hw

Thanks again, hope you will create a PR soon

**Comment by hussain** [comment]
Billing group seems valid option, even for the reporting menuitem itself from accounting. It does not make since to allow user to print partner ledger from partner, while Accounting=>Reporting=>Partner Ledger is not visible to the user.

Change applied for group billing, and hide partner (Thanks for the ref video).

I will post the PR soon.
