### ISSUE TITLE
[Odoo 15.0] - [om_account_followup] - Date Format on Report

### ISSUE THREAD

**Issue by haertwigfrank** [odoomates/odooapps#73]
**Issue:** The printed payment follow-up report is printing the date only in US date format while used in different language e.g german

**File:** /om_account_followup/report/followup_print.py

**Function:** def _lines_get_with_partner

**original code:** `line_data = {
                'name': line.move_id.name,
                'ref': line.ref,
                'date': line.date,
                'date_maturity': line.date_maturity,
                'balance': balance,
                'blocked': line.blocked,
                'currency_id': currency,
            }`

**possible change:** `line_data = {
                'name': line.move_id.name,
                'ref': line.ref,
                'date': format_date(self.env, line.date),
                'date_maturity': format_date(self.env, line.date_maturity),
                'balance': balance,
                'blocked': line.blocked,
                'currency_id': currency,
            }`
**other changes:** `from odoo.tools import format_date`

**Comment by odoomates** [comment]
Updated: https://github.com/odoomates/odooapps/commit/4480c58f13f7448b71532949f8b98d742e1cfbc8

Thanks for the code and looking forward for more such contributions <3
