### ISSUE TITLE
odoo 13.0 Bill Error 

### ISSUE THREAD

**Issue by msdeek** [odoomates/odooapps#8]
When i post Bill i get this Error:
  File "/odoo/custom/odoomates/odooapps/om_account_asset/models/account.py", line 24, in post
    return super(AccountMove, self).post(invoice=invoice)
TypeError: post() got an unexpected keyword argument 'invoice'

**Comment by odoomates** [comment]
Hi,
Fixed as you have reported it in apps.
Thanks
