### ISSUE TITLE
[16.0] Please migrate om_data_remove app to version 16.0

### ISSUE THREAD

**Issue by hansonc28** [odoomates/odooapps#88]
Hi Odoo Mates, can you please migrate the [om_data_remove](https://github.com/odoomates/odooapps/tree/15.0/om_data_remove) app to version 16.0? Yours is the cleanest and doesn't change a lot of my other settings...

Thanks for everything you do!

**Comment by odoomates** [comment]
Sure we will do it soon

**Comment by odoomates** [comment]
v16: https://github.com/odoomates/odooapps/tree/16.0/om_data_remove
