### ISSUE TITLE
[16.0] Unable to Create Cash transaction. (Error: Please install Accounting for this feature)

### ISSUE THREAD

**Issue by tanvir-git** [odoomates/odooapps#89]
![image_2022-11-15_010519816](https://user-images.githubusercontent.com/9804559/201744391-0a998253-7852-44f5-87e7-ba3209f686a7.png)

After installing "om_account_accountant" module. Go to Accounting App > From the Dashboard Cash Journal click "New Transaction" and this error occurs.

**Comment by davidliudev** [comment]
Same here

**Comment by tiagoclementemorgado** [comment]
@odoomates Any update?

**Comment by odoomates** [comment]
Fixed by: https://github.com/odoomates/odooapps/commit/969085cdb49c7c214f5ebbbe856f3f16f2fa8214
