### ISSUE TITLE
Suggestion: change in security

### ISSUE THREAD

**Issue by omalbastin** [odoomates/odooapps#9]
https://github.com/odoomates/odooapps/blob/64a188cd908c352bf7a3b1f8e6099eef88925e9d/accounting_pdf_reports/security/security.xml#L7

If you could have used the account.group_account_manager in implied ids, i believe it could be better. just a suggestion

**Comment by odoomates** [comment]
thanks for the suggestion, upon checking seems even odoo enterprise goes with this approach.
