### ISSUE TITLE
[16.0] Error when printing General Ledger Audit Report

### ISSUE THREAD

**Issue by leroborat** [odoomates/odooapps#90]
psycopg2.errors.UndefinedColumn: column l.analytic_account_id does not exist

To replicate

Accounting -> Reporting -> Audit Reports - General Ledger

**Comment by samirahmt2018** [comment]
just replace  
LEFT JOIN account_analytic_account aaa ON (aaa.id=l.analytic_account_id)\
with 
LEFT JOIN account_analytic_account aaa ON (aaa.id=l.account_id)\

on line 107 of file accounting_pdf_reports/report/report_general_ledger.py

**Comment by odoomates** [comment]
Fixed: https://github.com/odoomates/odooapps/commit/2b2b103533ba1c8fbb69cbecc06b9efbea9995ce
